# Generated by Django 5.2.5 on 2026-01-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=64)),
                ('machine_id', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
