# Generated by Django 5.2.5 on 2026-01-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_project_managers_alter_transaction_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
